In [2]:
import numpy as np
students = np.random.randint(50,101,size=(50,5))
students

array([[ 72,  73,  54,  85,  79],
       [ 95,  63,  70,  71,  97],
       [ 82,  67,  68,  96,  74],
       [ 87,  89,  65,  55,  51],
       [ 70,  74,  69,  83,  90],
       [ 64,  68,  89,  70,  82],
       [ 72,  79, 100,  57,  62],
       [ 92,  67,  73,  91,  67],
       [ 91,  57,  57,  72,  78],
       [ 70,  72,  73,  98,  92],
       [ 94,  90,  52,  75,  63],
       [ 62,  91,  51,  75,  52],
       [ 99,  59,  84,  53,  93],
       [ 66,  76,  88,  83,  53],
       [ 65,  90,  55,  55,  86],
       [ 98,  93,  92,  85,  91],
       [ 77,  95,  50,  59,  81],
       [ 75,  59,  60,  73,  56],
       [ 83,  68,  64,  87,  71],
       [ 91,  88,  69,  67,  54],
       [ 66,  77,  52,  54,  86],
       [ 93,  99,  80,  66,  90],
       [ 64,  50,  79,  80,  51],
       [ 87,  99,  50,  62,  57],
       [ 89,  95,  84,  57,  89],
       [ 94,  85,  92,  54,  59],
       [ 76,  70,  51,  84,  93],
       [ 59,  98,  56,  81,  74],
       [ 78,  56,  77,  74,  68],
       [ 95,  

In [3]:
students[0,0]
students[:1,:]
students[:1] #前一個學生
students[:2] #前2個學生
students[-5:] #最後5個學生

array([[ 63, 100,  55,  83,  80],
       [ 56,  89,  74,  67,  64],
       [ 82,  52,  90,  55,  92],
       [ 78,  85,  88,  81,  96],
       [ 85,  53,  91,  90,  60]])

In [4]:
students[:, 0] #第一科所有分數
students[:, -1] #最後一科所有分數

array([ 79,  97,  74,  51,  90,  82,  62,  67,  78,  92,  63,  52,  93,
        53,  86,  91,  81,  56,  71,  54,  86,  90,  51,  57,  89,  59,
        93,  74,  68,  98,  61,  72,  55,  56,  82,  87, 100,  66,  54,
        70,  58,  83,  99,  67,  81,  80,  64,  92,  96,  60])

In [ ]:
np.sum(students[:1]) #第一位學生總分
np.sum(students[:2], axis = 1) #前兩位學生總分
np.sum(students, axis = 1) #全班每位學生總分
np.sum(students, axis = 0) #全班每一科平均
np.median(students, axis = 0) #全班每一科中位數